# Generated by Django 2.1.7 on 2019-03-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
