# Generated by Django 2.1.7 on 2019-04-02 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190401_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='creater',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(blank=True, null=True, related_name='invited_user', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_open',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
