# Generated by Django 2.1.7 on 2019-04-15 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_event_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_first_user', to=settings.AUTH_USER_MODEL, verbose_name='First User')),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_second_user', to=settings.AUTH_USER_MODEL, verbose_name='Second User')),
            ],
            options={
                'verbose_name': 'Private Chat Room',
                'verbose_name_plural': 'Privat Chat Rooms',
            },
        ),
        migrations.CreateModel(
            name='PrivateChatMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Sent')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.PrivateChat', verbose_name='Private Chat Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
