# Generated by Django 2.1.7 on 2019-04-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_privatechat_privatechatmessages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatechat',
            options={'verbose_name': 'Private Chat Room', 'verbose_name_plural': 'Private Chat Rooms'},
        ),
        migrations.AlterModelOptions(
            name='privatechatmessages',
            options={'verbose_name': 'Private Chat Message', 'verbose_name_plural': 'Private Chat Messages'},
        ),
        migrations.AddField(
            model_name='privatechat',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
